Migrate csv download servlet to spring
yanagishima/yanagishima pull request #211
Opened 2020-12-15 13:33 UTC by ebyhr

Related to #184

2020-12-16 02:01 UTC, wyukawa requested changes

2020-12-16 02:01 UTC, wyukawa commented on src/main/java/yanagishima/servlet/CsvDownloadServlet.java
> +                                               datasource, datasource, user);
```
queryid, datasource, user
```

2020-12-16 02:05 UTC, ebyhr commented
@wyukawa You don't need to review this PR unless I request review. I will do it once it's ready.

2020-12-24 03:25 UTC, okue approved these changes
LGTM

2020-12-24 04:16 UTC, merged